theme: jekyll-theme-cayman

title: SHOGun
description: SHOGun Webmapping using Spring Boot

show_downloads: true

github:
  zip_url: https://github.com/terrestris/shogun/zipball/master
  tar_url: https://github.com/terrestris/shogun/tarball/master
